# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build nx-express-zod-starter`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t nx-express-zod-starter`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system nx-express-zod-starter && \
          adduser --system -G nx-express-zod-starter nx-express-zod-starter

COPY dist/nx-express-zod-starter nx-express-zod-starter
RUN chown -R nx-express-zod-starter:nx-express-zod-starter .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix nx-express-zod-starter --omit=dev -f install

CMD [ "node", "nx-express-zod-starter" ]
